version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "./server.sh"
    volumes:
    - .:/var/www
    env_file:
    - oauth_dev.env
    ports:
    - "8888:8888"
